### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Snoci** [drdre-08/discord-selfechobot#5]
i know its outdated, but it still works besides the fact that it doesn't copy images is there any way it can do this?

**Comment by drdre-08** [comment]
This should be possible by attaching the image (via [FileOptions)](https://discord.js.org/#/docs/main/stable/typedef/FileOptions) as a parameter when [sending](https://github.com/drdre-08/discord-selfechobot/blob/master/index.js#L97) the message.

See [here](https://discord.js.org/#/docs/discord.js/stable/class/DMChannel?scrollTo=send) for examples.
